### ISSUE TITLE
Don't try to run AWS tests on DrDr

### ISSUE THREAD

**Issue by greghendershott** [mflatt/s3-sync#1]
To fix [this](http://drdr.racket-lang.org/29593/racket/share/pkgs/s3-sync/tests/main.rkt) I think you'll need to change [this](https://github.com/mflatt/s3-sync/blob/master/tests/main.rkt#L24) from:

```
(unless bucket
  (error 'test-s3-sync "could not find `test/bucket' entry in: ~a" data-file))
;; remainder of tests/main.rkt
```

to be something like:

```
(when bucket
  ;; remainder of tests/main.rkt
)
```

I recently did similar in aws because there won't be any `~/.aws-tests-data` in the DrDr environment.

**Comment by mflatt** [comment]
Done, finally.
